version: "3.8"

networks:
  app_network: # Создаём пользовательскую сеть
    driver: bridge

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - app_network # Подключаем к сети

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - postgres_db
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: test_db
    ports:
      - "5000:5000"
    networks:
      - app_network # Подключаем к сети
